rocketmq:
  name-server: 192.168.0.105:9876

spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 36558563@qq.com #QQ邮箱
    password: ghvyzsuxhkxdbhdd #客户端授权码
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    from: 36558563@qq.com


